### PR TITLE
Update Bicep snippets from customrp to corerp

### LINKED ISSUE #158: Switch from Starters to raw resource definitions in docs

### LINKED ISSUE #175: hide or note "coming soon" for csi-driver for keyvault
that dev work is bumped to v0.13
we should hide this page (not delete) for now 
https://edge.radapp.dev/reference/resource-schema/core-schema/container-schema/volume/persistent/azure-keyvault-volume/

```
toc_hide: false
hide_summary: true
```

@vinayada1 @rynowak to triple-check that the functionality not supported in v0.12 is any kind of persistent volume for azure keyvault.

### PR DESCRIPTION
**Pull request by AaronCrawfis**
## Overview

- Update every Bicep file to use corerp resources
- Remove references to starters

## ToDo

- ~Update Dapr quickstart~
- ~Update eShop~
- ~Persistent volumes~

## Open Questions

- ~Do connectors need an `environment` property?~
   - Yes, added
- ~How does the `environment` parameter get passed into the file at deploy time?~
   - Currently automatically injected, will switch to better solution in future

### CODE REVIEW

**Comment by emily-potyraj** [comment]
> Do connectors need an environment property?

Yes, environment is a required property for connectors. 
For example: https://github.com/project-radius/radius/blob/main/test/functional/corerp/resources/testdata/corerp-resources-mongodb.bicep

> How does the environment parameter get passed into the file at deploy time?

- Current state: Right now, we require env id to be passed as a parameter via CLI for `rad deploy` 
  - e.g. `rad deploy todo.bicep -p environment="/planes/radius/local/resourcegroups/env1-rg/providers/applications.core/environments/env1" `
- Future state described in: [Issue radius-project/core-team#694](https://github.com/project-radius/radius/issues/2751)

**Comment by emily-potyraj** [comment]
@AaronCrawfis have you already tested deploying these snippets or do you want some help with that?

**Comment by AaronCrawfis** [comment]
> have you already tested deploying these snippets or do you want some help with that?

One thing we need to do to validate these changes is merge radius-project/core-team#484, then we can tackle any errors/warnings being generated.

Once this PR is merged then we can go through the usual tutorial/quickstart testing that we do as part of every release. We won't need to deploy all of these files.

**Review by mhaveliwala1 — DISMISSED** [review]

**Review by jasonviviano — APPROVED** [review]
LGTM

**Pull request merged**
