### PR TITLE
Add dropdown arrows to sections

### PR DESCRIPTION
**Pull request by AaronCrawfis**
Adds a dropdown arrow to sections

Also updates the CSS to make pages and sections look the same

### CODE REVIEW

**Review by willtsai — APPROVED** [review]

**Comment by Reshrahim** [comment]
@AaronCrawfis - This is great! When navigating I noticed that the page that has a dropdown doesn't get rendered in the right pane. On click, only the dropdown list in the left pane expands. Bird's eye view of the section is lost

**Comment by AaronCrawfis** [comment]
> @AaronCrawfis - This is great! When navigating I noticed that the page that has a dropdown doesn't get rendered in the right pane. On click, only the dropdown list in the left pane expands. Bird's eye view of the section is lost 

@Reshrahim Could you paste a screenshot and steps to recreate? Can get that fixed today. Thanks!

**Edit** (I just re-read, we intended to get rid of the overview page)

**Comment by Reshrahim** [comment]
ooh so this view is intentionally not available anymore on clicking Quickstarts?

image

**Comment by AaronCrawfis** [comment]
> ooh so this view is intentionally not available anymore on clicking Quickstarts?

For now, correct. Let's discuss later today on some ideas on how to bring a version of this page back.

**Pull request merged**
